# Generated by Django 2.2.5 on 2019-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.IntegerField()),
                ('kind', models.CharField(choices=[('DET', 'Detection'), ('CLA', 'Classification'), ('TAG', 'Tagging')], max_length=3)),
            ],
        ),
    ]
